# Generated by Django 6.0.2 on 2026-03-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiTextGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('system_message', models.CharField(max_length=255)),
                ('user_message', models.CharField(max_length=255)),
                ('response_message', models.CharField(max_length=255)),
                ('response_done', models.CharField(max_length=255)),
                ('response_done_reason', models.CharField(max_length=255)),
                ('response_total_duration', models.CharField(max_length=255)),
                ('response_load_duration', models.CharField(max_length=255)),
                ('response_prompt_eval_count', models.CharField(max_length=255)),
                ('response_prompt_eval_duration', models.CharField(max_length=255)),
                ('response_eval_count', models.CharField(max_length=255)),
                ('response_eval_duration', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'AiTextGeneration',
                'verbose_name_plural': 'AiTextGenerations',
            },
        ),
    ]
