# Generated by Django 6.0.2 on 2026-03-27 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_prompt_generations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiImageGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('comfyui_prompt_id', models.CharField(max_length=255)),
                ('comfyui_output_path', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('image_url', models.CharField(max_length=255)),
                ('ai_prompt_generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_image_generations', to='ai_prompt_generations.aipromptgeneration')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AiImageGeneration',
                'verbose_name_plural': 'AiImageGenerations',
            },
        ),
    ]
