# Generated by Django 6.0.2 on 2026-03-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiTextGenerationPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('system_role', models.CharField(max_length=255)),
                ('system_message', models.CharField(max_length=255)),
                ('user_role', models.CharField(max_length=255)),
                ('user_message', models.CharField(max_length=255)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'AiTextGenerationPrompt',
                'verbose_name_plural': 'AiTextGenerationPrompts',
            },
        ),
    ]
